
module Heros exposing (..)


type HeroVec
    = Position { x : Float, y : Float }
    | NoPosition


type alias Hero =
    { name : String
    , img_url : String
    , vec : HeroVec
    }


initHeros : List Hero
initHeros =[
{name="Anti-Mage"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/antimage_icon.png"
,vec=Nothing,}
{name="Axe"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/axe_icon.png"
,vec=Nothing,}
{name="Bane"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/bane_icon.png"
,vec=Nothing,}
{name="Bloodseeker"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/bloodseeker_icon.png"
,vec=Nothing,}
{name="Crystal Maiden"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/crystal_maiden_icon.png"
,vec=Nothing,}
{name="Drow Ranger"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/drow_ranger_icon.png"
,vec=Nothing,}
{name="Earthshaker"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/earthshaker_icon.png"
,vec=Nothing,}
{name="Juggernaut"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/juggernaut_icon.png"
,vec=Nothing,}
{name="Mirana"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/mirana_icon.png"
,vec=Nothing,}
{name="Morphling"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/morphling_icon.png"
,vec=Nothing,}
{name="Shadow Fiend"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/nevermore_icon.png"
,vec=Nothing,}
{name="Phantom Lancer"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/phantom_lancer_icon.png"
,vec=Nothing,}
{name="Puck"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/puck_icon.png"
,vec=Nothing,}
{name="Pudge"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/pudge_icon.png"
,vec=Nothing,}
{name="Razor"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/razor_icon.png"
,vec=Nothing,}
{name="Sand King"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/sand_king_icon.png"
,vec=Nothing,}
{name="Storm Spirit"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/storm_spirit_icon.png"
,vec=Nothing,}
{name="Sven"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/sven_icon.png"
,vec=Nothing,}
{name="Tiny"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/tiny_icon.png"
,vec=Nothing,}
{name="Vengeful Spirit"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/vengefulspirit_icon.png"
,vec=Nothing,}
{name="Windranger"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/windrunner_icon.png"
,vec=Nothing,}
{name="Zeus"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/zuus_icon.png"
,vec=Nothing,}
{name="Kunkka"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/kunkka_icon.png"
,vec=Nothing,}
{name="Lina"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/lina_icon.png"
,vec=Nothing,}
{name="Lion"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/lion_icon.png"
,vec=Nothing,}
{name="Shadow Shaman"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/shadow_shaman_icon.png"
,vec=Nothing,}
{name="Slardar"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/slardar_icon.png"
,vec=Nothing,}
{name="Tidehunter"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/tidehunter_icon.png"
,vec=Nothing,}
{name="Witch Doctor"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/witch_doctor_icon.png"
,vec=Nothing,}
{name="Lich"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/lich_icon.png"
,vec=Nothing,}
{name="Riki"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/riki_icon.png"
,vec=Nothing,}
{name="Enigma"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/enigma_icon.png"
,vec=Nothing,}
{name="Tinker"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/tinker_icon.png"
,vec=Nothing,}
{name="Sniper"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/sniper_icon.png"
,vec=Nothing,}
{name="Necrophos"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/necrolyte_icon.png"
,vec=Nothing,}
{name="Warlock"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/warlock_icon.png"
,vec=Nothing,}
{name="Beastmaster"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/beastmaster_icon.png"
,vec=Nothing,}
{name="Queen of Pain"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/queenofpain_icon.png"
,vec=Nothing,}
{name="Venomancer"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/venomancer_icon.png"
,vec=Nothing,}
{name="Faceless Void"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/faceless_void_icon.png"
,vec=Nothing,}
{name="Wraith King"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/skeleton_king_icon.png"
,vec=Nothing,}
{name="Death Prophet"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/death_prophet_icon.png"
,vec=Nothing,}
{name="Phantom Assassin"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/phantom_assassin_icon.png"
,vec=Nothing,}
{name="Pugna"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/pugna_icon.png"
,vec=Nothing,}
{name="Templar Assassin"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/templar_assassin_icon.png"
,vec=Nothing,}
{name="Viper"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/viper_icon.png"
,vec=Nothing,}
{name="Luna"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/luna_icon.png"
,vec=Nothing,}
{name="Dragon Knight"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/dragon_knight_icon.png"
,vec=Nothing,}
{name="Dazzle"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/dazzle_icon.png"
,vec=Nothing,}
{name="Clockwerk"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/rattletrap_icon.png"
,vec=Nothing,}
{name="Leshrac"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/leshrac_icon.png"
,vec=Nothing,}
{name="Nature's Prophet"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/furion_icon.png"
,vec=Nothing,}
{name="Lifestealer"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/life_stealer_icon.png"
,vec=Nothing,}
{name="Dark Seer"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/dark_seer_icon.png"
,vec=Nothing,}
{name="Clinkz"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/clinkz_icon.png"
,vec=Nothing,}
{name="Omniknight"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/omniknight_icon.png"
,vec=Nothing,}
{name="Enchantress"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/enchantress_icon.png"
,vec=Nothing,}
{name="Huskar"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/huskar_icon.png"
,vec=Nothing,}
{name="Night Stalker"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/night_stalker_icon.png"
,vec=Nothing,}
{name="Broodmother"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/broodmother_icon.png"
,vec=Nothing,}
{name="Bounty Hunter"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/bounty_hunter_icon.png"
,vec=Nothing,}
{name="Weaver"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/weaver_icon.png"
,vec=Nothing,}
{name="Jakiro"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/jakiro_icon.png"
,vec=Nothing,}
{name="Batrider"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/batrider_icon.png"
,vec=Nothing,}
{name="Chen"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/chen_icon.png"
,vec=Nothing,}
{name="Spectre"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/spectre_icon.png"
,vec=Nothing,}
{name="Ancient Apparition"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/ancient_apparition_icon.png"
,vec=Nothing,}
{name="Doom"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/doom_bringer_icon.png"
,vec=Nothing,}
{name="Ursa"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/ursa_icon.png"
,vec=Nothing,}
{name="Spirit Breaker"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/spirit_breaker_icon.png"
,vec=Nothing,}
{name="Gyrocopter"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/gyrocopter_icon.png"
,vec=Nothing,}
{name="Alchemist"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/alchemist_icon.png"
,vec=Nothing,}
{name="Invoker"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/invoker_icon.png"
,vec=Nothing,}
{name="Silencer"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/silencer_icon.png"
,vec=Nothing,}
{name="Outworld Devourer"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/obsidian_destroyer_icon.png"
,vec=Nothing,}
{name="Lycan"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/lycan_icon.png"
,vec=Nothing,}
{name="Brewmaster"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/brewmaster_icon.png"
,vec=Nothing,}
{name="Shadow Demon"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/shadow_demon_icon.png"
,vec=Nothing,}
{name="Lone Druid"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/lone_druid_icon.png"
,vec=Nothing,}
{name="Chaos Knight"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/chaos_knight_icon.png"
,vec=Nothing,}
{name="Meepo"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/meepo_icon.png"
,vec=Nothing,}
{name="Treant Protector"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/treant_icon.png"
,vec=Nothing,}
{name="Ogre Magi"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/ogre_magi_icon.png"
,vec=Nothing,}
{name="Undying"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/undying_icon.png"
,vec=Nothing,}
{name="Rubick"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/rubick_icon.png"
,vec=Nothing,}
{name="Disruptor"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/disruptor_icon.png"
,vec=Nothing,}
{name="Nyx Assassin"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/nyx_assassin_icon.png"
,vec=Nothing,}
{name="Naga Siren"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/naga_siren_icon.png"
,vec=Nothing,}
{name="Keeper of the Light"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/keeper_of_the_light_icon.png"
,vec=Nothing,}
{name="Io"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/wisp_icon.png"
,vec=Nothing,}
{name="Visage"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/visage_icon.png"
,vec=Nothing,}
{name="Slark"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/slark_icon.png"
,vec=Nothing,}
{name="Medusa"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/medusa_icon.png"
,vec=Nothing,}
{name="Troll Warlord"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/troll_warlord_icon.png"
,vec=Nothing,}
{name="Centaur Warrunner"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/centaur_icon.png"
,vec=Nothing,}
{name="Magnus"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/magnataur_icon.png"
,vec=Nothing,}
{name="Timbersaw"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/shredder_icon.png"
,vec=Nothing,}
{name="Bristleback"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/bristleback_icon.png"
,vec=Nothing,}
{name="Tusk"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/tusk_icon.png"
,vec=Nothing,}
{name="Skywrath Mage"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/skywrath_mage_icon.png"
,vec=Nothing,}
{name="Abaddon"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/abaddon_icon.png"
,vec=Nothing,}
{name="Elder Titan"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/elder_titan_icon.png"
,vec=Nothing,}
{name="Legion Commander"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/legion_commander_icon.png"
,vec=Nothing,}
{name="Techies"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/techies_icon.png"
,vec=Nothing,}
{name="Ember Spirit"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/ember_spirit_icon.png"
,vec=Nothing,}
{name="Earth Spirit"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/earth_spirit_icon.png"
,vec=Nothing,}
{name="Underlord"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/abyssal_underlord_icon.png"
,vec=Nothing,}
{name="Terrorblade"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/terrorblade_icon.png"
,vec=Nothing,}
{name="Phoenix"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/phoenix_icon.png"
,vec=Nothing,}
{name="Oracle"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/oracle_icon.png"
,vec=Nothing,}
{name="Winter Wyvern"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/winter_wyvern_icon.png"
,vec=Nothing,}
{name="Arc Warden"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/arc_warden_icon.png"
,vec=Nothing,}
{name="Monkey King"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/monkey_king_icon.png"
,vec=Nothing,}
{name="Dark Willow"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/dark_willow_icon.png"
,vec=Nothing,}
{name="Pangolier"
,img_url="https://api.opendota.com//apps/dota2/images/heroes/pangolier_icon.png"
,vec=Nothing,}
]